# mysql 的数据库配置
spring:
  datasource:
    url: jdbc:mysql://172.17.210.180:3306/hrms?useUnicode=true&characterEncoding=UTF-8
    username: hrms
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver